### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by BlackRookSix** [mucommunity/mucommunity#7]
Need recommendations for a Site name.  I have hosting servers with unlimited space, database and bandwidth, professionally managed, so I can host us for free at least to get started. 

MushNexus.org  
MuCommunity.org
MuGames.org
MUSHGames.org

I like the first.  Votes? Suggestions?  I can have this up and running today, and start setting up SFTP access for developers, start installing needed software packages, etc.

**Comment by tkrajcar** [comment]
This isn't a MUSH-specific directory, so 'MU' is probably more appropriate.

That said, I actually want to table this for a bit, as I've got some inquiries in to some people that I need to hear back from first that could affect the name question. I'll note here in a couple days with the results.

Regarding the hosting perspective, I appreciate the resources volunteer - we're set on that front. The needs for this go a bit beyond your typical shared hosting package to optimize for developer productivity. I'd like to use a PaaS like Heroku if the finances work out. If not I'll rig it up on AWS.

**Comment by tkrajcar** [comment]
@BlackRookSix No response on my inquiries, so I think we can go forward with grabbing a name. MUNexus.org is my favorite of the options so far.

**Comment by BlackRookSix** [comment]
Okay, I will start the process of retaining that domain (MUNexus.org) this morning.

**Comment by BlackRookSix** [comment]
Seems like MUNexus.org is registered, last year, by someone in Panama. 

mucommunity.org is available?

**Comment by tkrajcar** [comment]
MUCommunity works for me.

**Comment by tkrajcar** [comment]
Registered, repo moved to mucommunity/mucommunity. :+1:
